### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JumpySWE**
Grammatical fixes.
Requirements changed to Compatibility, for simplicity.
Added browser logos to improve visual appearance.
AMO link no longer forces the en-US version.
GPLv3 now links to COPYING.

### CODE REVIEW

**Comment by sylingd** [comment]
The Mozilla's review is too slow, so I think, the waiting time to experence new version for users who installed the self-distributed version, is much shorter than installing from AMO

**Comment by JumpySWE** [comment]
Are you referring to the "a bit earlier" statement?

**Comment by sylingd** [comment]
Yes, I refering it

**Comment by JumpySWE** [comment]
Tried rewriting it. How does that sound?

**Comment by sylingd** [comment]
Sounds good

**Pull request merged**
